### PR TITLE
[PR] Break up the main class into smaller classes

### PR DESCRIPTION
**Pull request by philcable**

### CODE REVIEW

**Comment by philcable** [comment]
@jeremyfelt Let me know if this organization makes any kind of sense. If so, #reviewmerge?

**Comment by jeremyfelt** [comment]
I think this is a good start. A few thoughts:

* I like the idea of keeping the original `WSUWP_People_Directory` class the same rather than changing to `WSUWP_People`. It matches the plugin name and is the main class that can act as a controller for some of the other things that are going on.
* I would consider splitting the taxonomies out into individual classes. This makes it easier to manage meta in the future if needed. This is the approach I recently took for Grad School. See https://github.com/washingtonstateuniversity/gradschool.wsu.edu/tree/master/includes
* I would keep the post meta keys attached to the `WSUWP_People_Post_Type` class as it fits as part of a logical grouping. If the post type disappears, they all disappear.

**Comment by philcable** [comment]
@jeremyfelt Thanks for the suggestions!

I shuffled a few other pieces into the `WSUWP_People_Post_Type` class, as it seemed to follow the same logic as keeping the post meta keys attached.

**Comment by jeremyfelt** [comment]
:+1: Good stuff!

**Pull request merged**
