### PR TITLE
[PR] Profile editor UX rebuild

### PR DESCRIPTION
**Pull request by philcable**
I thought it would be best to get eyes on this before moving on to the photo collection and taxonomy handling, just in case there are any concerns with the direction or execution.

### CODE REVIEW

**Comment by philcable** [comment]
@jeremyfelt  #reviewmerge?

**Comment by jeremyfelt** [comment]
This is looking really good! I think the new content editable approach is on the right track. I really like the idea of profile information being edited in a more natural way than a bunch of ugly input boxes.

I noticed a couple things when playing around:

* It'd be nice if we could come up with a subtle but useful way to hint that the content is editable while still displaying as if it was being used on the front page. I poked around for some best practices, but haven't found anything useful yet. I don't know if shading them slightly is enough or if we need a blurb explaining how to edit. I don't think there's a blocker anywhere here, but something that we should be thinking of.
* There is still a small timing issue between the main site and secondary site. When you edit on a secondary site and refresh the main site, it always works. When you edit on the main site and refresh on the secondary site, it doesn't immediately reflect. There's **definitely** a server configuration that needs to be updated to help with that. I'll start poking around there.
* It's possible to remove title completely in the UI, though it looks like the default will always come back.

And... I'm not sure how realistic this is, but is it possible to match the markup more closely to a person card and put `contenteditable` directly on the `span` and other elements. I played around a bit in a CodePen and it seems to work in Chrome, but I'm not sure if there are any other gotachas.

```
<div class="contact">
	<span contenteditable=true class="title"><?php echo wp_kses_post( $display['title'] ); ?></span>
	<span contenteditable=true class="email"><a href="mailto:<?php echo esc_attr( $display['email'] ); ?>">
		<?php echo esc_html( $display['email'] ); ?></a>
	</span>
	<span contenteditable=true class="phone"><?php echo esc_html( $display['phone'] ); ?></span>
	<span contenteditable=true class="office"><?php echo esc_html( $display['office'] ); ?></span>
   // ... etc
```

If that's possible, then it might be nice to output the `<input>` elements in a separate place so that the HTML output can be separated a bit. I guess in a perfect world, we could use a single HTML template for both areas.

Sorry for the brainstorm dump! :)

**Comment by philcable** [comment]
Thanks! That all sounds good!

I'll make a couple more commits to address the title issue and match the markup more closely.

I don't seem to be experiencing the timing issue in my setup ¯\_(ツ)_/¯. However, testing that did uncover a potential issue with post titles. Since they're stored on the spoke sites, and that local version is used for front-end views, a change to the primary record's post title won't reflect on the front-end of a spoke site. Hopefully that won't happen too often, but it's something we should think about.

**Comment by philcable** [comment]
@jeremyfelt I think this is ready for another #review!

**Pull request merged**
